on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Build
        run: |
          echo "Building site assets..."
